name: Deploy Debug to Railway (temporary)

on:
  workflow_dispatch:

jobs:
  debug-deploy:
    runs-on: ubuntu-latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - language: English
            code: en
            model: facebook/wav2vec2-large-xlsr-53-english

    steps:
      - uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Debug Railway auth (temporary)
        run: |
          echo "=== railway version ==="
          railway --version || true
          echo "=== railway whoami (verifies token) ==="
          railway whoami || echo "railway whoami failed (token/auth issue)"
          echo "=== attempt to list projects/services (best-effort) ==="
          railway projects || railway project || railway services || echo "list failed"

      - name: Deploy (non-interactive)
        run: |
          set -e
          # Use explicit project id if provided
          if [ -n "$RAILWAY_PROJECT_ID" ]; then
            echo "Running: railway up --service soundmirror-${{ matrix.code }} --detach --project-id $RAILWAY_PROJECT_ID"
            railway up --service "soundmirror-${{ matrix.code }}" --detach --project-id "$RAILWAY_PROJECT_ID"
            railway variables set MODEL_ID="${{ matrix.model }}" LANGUAGE="${{ matrix.code }}" --service "soundmirror-${{ matrix.code }}" --project-id "$RAILWAY_PROJECT_ID"
          else
            echo "Running: railway up --service soundmirror-${{ matrix.code }} --detach (no project id supplied)"
            railway up --service "soundmirror-${{ matrix.code }}" --detach || railway up --detach
            railway variables set MODEL_ID="${{ matrix.model }}" LANGUAGE="${{ matrix.code }}" --service "soundmirror-${{ matrix.code }}"
          fi
